# Generated by Django 5.1.3 on 2024-11-21 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'event')},
        ),
    ]
